value = 'expr_4_lag*objvar + expr_5_lag*objvar + expr_6_lag*objvar - log(objvar)'
objvarkey ='objvar'
lwrkey ='net_name_g2.ssrate_lwr_default'
uprkey ='net_name_g2.ssrate_upr_default'
lwr ='net_name_g2.ssrate_lwr_default'
pnl_sum ='pnl_coefficient'
