#This file contains multiple values and keys for the optimization variables
#This file is automatically generated
value = "np.array([coord_x_link_4, coord_y_link_4])"
key = "np.array([coord_x, coord_y])"