#This file contains multiple values and keys for the optimization variables
#This file is automatically generated
value = "np.array([coord_x_link_3, coord_y_link_3])"
key = "np.array([coord_x, coord_y])"