node_4 = {}
node_4["prev_hop"]="None"
node_4["next_hop"]="['node_5']"
node_5 = {}
node_5["prev_hop"]="['node_4']"
node_5["next_hop"]="['node_6']"
node_6 = {}
node_6["prev_hop"]="['node_5']"
node_6["next_hop"]="['node_7']"
node_7 = {}
node_7["prev_hop"]="['node_6']"
node_7["next_hop"]="None"
